# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 676becbbe02faa7c44ce187ceb67561d0830aa4bb3dec30b165b93e670f3e507b1b5706ec61051caa1d3a85d86da5b3e3b8d519e89b9bb96c18a561b70d1e0e4

test:
  secret_key_base: 920224a51c63d55c4f2f50a59fa9e4e902e1d9c3fc93a81697bfc4a908f2ecf38b1b4703d5e7729181805d49c6b2f344e212b2ee204128f815b2faf6ce0c7b60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
