# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Trail.destroy_all
User.destroy_all

trails = Trail.create([
  { name: "Runyon Canyon Trail",
    location: "Hollywood Boulevard, CA",
    level: "moderate",
    distance: "2.5 miles",
    lat: 34.105240,
    lng: -118.349982 },
  { name: "Mount Hollywood Trail",
    location: "Los Angeles, CA",
    level: "moderate",
    distance: "1.2 miles",
    lat: 34.132848,
    lng: -118.284421},
  { name: "Griffith Park Hollywood Sign Trail",
    location: "Griffith Park, Los Angeles, CA",
    level: "easy",
    distance: "8.7 miles",
    lat: 34.130858,
    lng: -118.283735},
  { name: "Cahuenga Peak Loop",
    location: "Griffith Park, Los Angeles, CA",
    level: "moderate",
    distance: "3.7 miles",
    lat: 34.133094,
    lng: -118.337444},
  { name: "Bronson Caves",
    location: "Griffith Park, Los Angeles, CA",
    level: "easy",
    distance: "0.6 miles",
    lat: 34.123518,
    lng: -118.313019},
  { name: "Old Zoo Trail",
    location: "Griffith Park, Los Angeles, CA",
    level: "moderate",
    distance: "7.1 miles",
    lat: 34.154075,
    lng: -118.308744},
  { name: "Kenneth Hahn Recreation Area",
    location: "Los Angeles, CA",
    level: "easy",
    distance: "2.8 miles",
    lat: 34.012669,
    lng: -118.371014},
  { name: "Inspiration Point Trail",
    location: "Los Angeles, CA",
    level: "easy",
    distance: "2.1 miles",
    lat: 34.054701,
    lng: -118.511581},
  { name: "San Vincente Mountain: Old Nike Missile Site Trail",
    location: "Los Angeles, CA",
    distance: "10.0 miles",
    lat: 34.128057,
    lng: -118.503274},
  { name: "Veterans Park Trail",
    location: "Veterans Memorial Park, Los Angeles, CA",
    level: "hard",
    distance: "2.2 miles",
    lat: 34.326138,
    lng: -118.418710},
  { name: "Oak Pass And Los Pinetos Trails",
    location: "Placerita Canyon State Park, Newhall, CA",
    level: "moderate",
    distance: "7.0 miles",
    lat: 34.376234,
    lng: -118.467413},
  { name: "Wilson Canyon Trail",
    location: "Wilson Park, Sylmar, CA",
    level: "hard",
    distance: "2.8 miles",
    lat: 34.324857,
    lng: -118.438760},
  { name: "Heritage Trailand Botany Loop Trail",
    location: "Placerita Canyon State Park",
    level: "easy",
    distance: "4.8 miles",
    lat: 34.375101,
    lng: -118.466727},
  { name: "O'Melveny Bee Canyon Trail",
    location: "O Melveny Park, Granada Hills, CA", level: "moderate",
    distance: "4.0 miles",
    lat: 34.309480,
    lng: -118.510147},
  { name: "Mission Point",
    location: "O Melveny Park, Los Angeles, CA",
    level: "moderate",
    distance: "4.4 miles",
    lat: 34.306592,
    lng: -118.518210},
  { name: "Bunker Hill Steps",
    location: "Los Angeles, CA",
    level: "easy",
    distance: "0.1 miles",
    lat: 34.050972,
    lng: -118.254807},
  { name: "Lake Balboa Park",
    location: "Lake Balboa Park, Los Angeles, CA", level: "moderate",
    distance: "1.4 miles",
    lat: 34.183993,
    lng: -118.492471},
  { name: "Inspiration Point Trail",
    location: "Will Rogers Historic State Park, Los Angeles, CA",
    level: "easy",
    distance: "2.4 miles",
    lat: 34.055022,
    lng: -118.514012},
  { name: "Mandeville Canyon Trail",
    location: "Los Angeles, CA",
    level: "moderate",
    distance: "7.2 miles",
    lat: 34.129280,
    lng: -118.314716
  }

])

user = User.create({
  firstname: "admin",
  lastname: "admin",
  username: "admin",
  email:"kaylinishime@gmail.com",
  password: "hello1234",
  password_confirmation: "hello1234"
})
